"""Update pie table

Revision ID: d40c63d7bdd8
Revises: 8a55d0288387
Create Date: 2024-01-06 12:58:55.041270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d40c63d7bdd8"
down_revision: Union[str, None] = "8a55d0288387"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pies", "nutritional_value", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pies", "nutritional_value", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
